### ISSUE TITLE
Suggestion:Add more features

### ISSUE THREAD

**Issue by swetlover** [ennvina/silentrotate#10]
Hello,this addons is very nice,In actual use, if the addons has the following functions, it will be more practical.
1. In the current version, the spelll cooldown time adopts a progress bar, and the accurate remaining time cannot be seen, so whether it is possible to directly use numbers to display the spell cooldown time.
2. In the Loatheb combat, RaidLeader will assign the queue of the healers, I want to be able to directly see who is first, who is second, and so on. So is it possible to add a sequence number before the player's name.
3. It would be very useful if you can see the spell being cast by the healer and show the  remaining time .
4. The Mind Control spell sometimes may be resisted,so a fail_announce is necessary.
Thanks！

**Comment by ennvina** [comment]
Hello and thank you for your feedback.

1. I agree that the remaining time could be useful and it’s something I want to add in the near future. However I do not want to saturate the UI with too much information so it would be an option.
2. Adding the player index before the name is very easy to add so I might add an option for this.
3. This feature is interesting but it needs some significant changes so I’m not sure if I can/will do it soon.
4. You are right but I kind of abandoned the Razuvious mode for now. There are too many hurdles to overcome, like detecting when the MC breaks early, detecting when an add becomes un-controllable, etc. I think the addon loses a lot of value when too many problems may happen. Currently, most guilds clear the voice comms so that the priests can give those details quickly, which is better than relying on an addon, in my opinion.

**Comment by swetlover** [comment]
Agree with your opinion, thanks for your work.

**Comment by ennvina** [comment]
The player index has been added. Make sure to download SilentRotate 0.6.2-beta and please tell me if it looks like what you wanted.
